# justfile

# Configuration
# 'command emacs' forces the shell to bypass aliases/functions and use the binary
emacs_bin := "command emacs"
init_dir := "."

# Directories generated by Emacs to be cleaned
trash_dirs := "elpa eln-cache auto-save-list transient" # server .cask"

# Files generated by Emacs to be cleaned
trash_files := "custom.el history" # recentf .lsp-session-v1"

# List available commands
default:
    @just --list

# Launch Emacs with the current config (bypassing your client alias)
run:
    {{emacs_bin}} --init-directory {{init_dir}}

# Launch Emacs with --debug-init to catch startup errors
debug:
    {{emacs_bin}} --init-directory {{init_dir}} --debug-init

# Launch in terminal mode (no GUI)
cli:
    {{emacs_bin}} --init-directory {{init_dir}} -nw

# Delete all compiled artifacts, packages, and history
clean:
    @echo "🧹 Cleaning runtime artifacts..."
    rm -rf {{trash_dirs}}
    rm -f {{trash_files}}
    # Find and delete all compiled elisp files recursively
    # find . -name "*.elc" -delete
    @echo "✨ Clean slate ready."

# Search for TODOs in .el files (ignores build dirs)
todos:
    @echo "📝 Scanning for TODOs..."
    @grep -rn --color=always "TODO" . \
        --include="*.el" \
        --exclude-dir={elpa,straight,var,etc,eln-cache,.git,auto-save-list,tree-sitter} \
        || echo "No TODOs found!"

# Re-compile everything (clean then run)
reset: clean run
