# justfile — Ratatoskr Emacs configuration.
#
# The recipes live in just/*.just, imported flat below: `import' splices them into
# this namespace, so every target is still `just <name>' with no module prefix.
# That is deliberate — those invocation strings are a public API here, named by
# README.org, AGENTS.md, .githooks/pre-commit, scripts/are-verify.sh and CI. `mod'
# would rename them all to `just test::ert' (D-013).
#
#   just/emacs.just        run, load, compile, clean
#   just/test.just         lint and the test suites
#   just/are.just          ARE entry points (.are/INDEX.md)
#   just/deps.just         install-deps dispatcher, check-deps
#   just/deps-arch.just    pacman + yay
#   just/deps-debian.just  apt-get + language toolchains
#   just/tools.just        repomix

# Configuration
# Emacs binary: set EMACS_BIN to override per machine; otherwise the first
# existing binary wins (Arch: /usr/bin/emacs, Ubuntu snap: /snap/bin/emacs),
# with a PATH lookup as last resort. Absolute paths dodge shell aliases
# (e.g. emacs=emacsclient on Arch).
emacs_bin := env("EMACS_BIN", `for p in /usr/bin/emacs /snap/bin/emacs; do [ -x "$p" ] && { echo "$p"; exit; }; done; command -v emacs`)
init_dir := "."

# Distro family, from /etc/os-release. `install-deps' dispatches on these; ID_LIKE
# is what catches the derivatives (Manjaro/EndeavourOS say arch, Mint/Pop say
# ubuntu/debian). Both are empty-safe: an absent os-release yields "unknown".
os_id := `. /etc/os-release 2>/dev/null; echo "${ID:-unknown}"`
os_like := `. /etc/os-release 2>/dev/null; echo "${ID_LIKE:-}"`

# Directories generated by Emacs to be cleaned
trash_dirs := "elpaca eln-cache auto-save-list transient elpa"

# Files generated by Emacs to be cleaned
trash_files := "custom.el history"

import 'just/emacs.just'
import 'just/test.just'
import 'just/are.just'
import 'just/deps.just'
import 'just/deps-arch.just'
import 'just/deps-debian.just'
import 'just/tools.just'

# List available commands
default:
    @just --list
