# justfile

# Configuration
# Emacs binary: set EMACS_BIN to override per machine; otherwise the first
# existing binary wins (Arch: /usr/bin/emacs, Ubuntu snap: /snap/bin/emacs),
# with a PATH lookup as last resort. Absolute paths dodge shell aliases
# (e.g. emacs=emacsclient on Arch).
emacs_bin := env("EMACS_BIN", `for p in /usr/bin/emacs /snap/bin/emacs; do [ -x "$p" ] && { echo "$p"; exit; }; done; command -v emacs`)
init_dir := "."

# Directories generated by Emacs to be cleaned
trash_dirs := "elpaca eln-cache auto-save-list transient elpa"

# Files generated by Emacs to be cleaned
trash_files := "custom.el history"

# List available commands
default:
    @just --list

# Launch Emacs with the current config
run:
    {{emacs_bin}} --init-directory {{init_dir}}

# Launch Emacs with --debug-init to catch startup errors
debug:
    {{emacs_bin}} --init-directory {{init_dir}} --debug-init

# Launch in terminal mode (no GUI)
cli:
    {{emacs_bin}} --init-directory {{init_dir}} -nw

# Byte-compile a single .el file for syntax checking (removes .elc after)
check file:
    {{emacs_bin}} --init-directory {{init_dir}} --batch --eval "(byte-compile-file \"{{file}}\")" ; rm -f "{{file}}c"

# Batch-load a single module to verify it parses
load file:
    {{emacs_bin}} --init-directory {{init_dir}} --batch -l "{{file}}"

# Full batch init (loads early-init + init; slow on first run due to elpaca)
batch:
    {{emacs_bin}} --init-directory {{init_dir}} --batch -l early-init.el -l init.el

# Delete all compiled artifacts, packages, and history
clean:
    @echo "Cleaning runtime artifacts..."
    rm -rf {{trash_dirs}}
    rm -f {{trash_files}}
    find . -name "*.elc" -not -path "./elpaca/*" -delete 2>/dev/null || true
    @echo "Clean slate ready."

# Search for TODOs in .el files (ignores build dirs)
todos:
    @grep -rn --color=always "TODO" . \
        --include="*.el" \
        --exclude-dir={elpaca,straight,var,etc,eln-cache,.git,auto-save-list,tree-sitter} \
        || echo "No TODOs found!"

# Full reset: clean then run
reset: clean run

# Install nerd-icons fonts (one-time setup)
install-fonts:
    {{emacs_bin}} --init-directory {{init_dir}} --batch -l early-init.el -l init.el --eval "(nerd-icons-install-fonts t)"

# Install tree-sitter grammars from treesit-language-source-alist
install-grammars:
    {{emacs_bin}} --init-directory {{init_dir}} --batch -l early-init.el -l init.el --eval "(mapc (lambda (src) (treesit-install-language-grammar (car src))) treesit-language-source-alist)"

# Generate elpaca lockfile
lock:
    {{emacs_bin}} --init-directory {{init_dir}} --batch -l early-init.el -l init.el --eval "(elpaca-lock)"

# Update all packages and regenerate lockfile
update:
    {{emacs_bin}} --init-directory {{init_dir}} --batch -l early-init.el -l init.el --eval "(progn (elpaca-update-all) (elpaca-lock))"

# Install system dependencies (Arch Linux)
install-deps:
    #!/usr/bin/env bash
    set -euo pipefail

    pacman_pkgs=(
        # Core tools
        git ripgrep fd enchant shfmt editorconfig-core-c
        # Language servers & formatters
        python-black prettier gopls pyright go-tools
        # Dev tools
        rustup python-pytest terraform kubectl docker hugo delve
        # SQL client (ejc-sql drives JDBC via a Clojure nREPL)
        jdk-openjdk leiningen
        # Org LaTeX math preview (latex + dvisvgm + org preamble packages:
        # wrapfig/capt-of -> latexextra, ulem -> plaingeneric)
        texlive-binextra texlive-latex texlive-latexrecommended
        texlive-latexextra texlive-plaingeneric
    )

    aur_pkgs=(claude-code-acp gomodifytags)

    # --- Pacman packages ---
    missing_pacman=()
    for pkg in "${pacman_pkgs[@]}"; do
        if ! pacman -Q "$pkg" &>/dev/null; then
            missing_pacman+=("$pkg")
        fi
    done

    if [ ${#missing_pacman[@]} -gt 0 ]; then
        echo "Missing pacman packages: ${missing_pacman[*]}"
        sudo pacman -S "${missing_pacman[@]}"
    else
        echo "All pacman packages already installed."
    fi

    # --- AUR packages ---
    missing_aur=()
    for pkg in "${aur_pkgs[@]}"; do
        if ! yay -Q "$pkg" &>/dev/null; then
            missing_aur+=("$pkg")
        fi
    done

    if [ ${#missing_aur[@]} -gt 0 ]; then
        echo "Missing AUR packages: ${missing_aur[*]}"
        yay -S "${missing_aur[@]}"
    else
        echo "All AUR packages already installed."
    fi

    # --- Rust toolchain (rustup, not pacman — avoids binary conflicts) ---
    rustup toolchain install nightly 2>/dev/null || true
    rustup component add rust-analyzer --toolchain nightly 2>/dev/null || true
    rustup component add clippy 2>/dev/null || true
    rustup component add rustfmt --toolchain nightly 2>/dev/null || true

    echo ""
    echo "Done."

# Run convention linting (fast, no Emacs needed)
lint:
    ./scripts/lint.sh

# Byte-compile all .el files to catch errors
compile:
    #!/usr/bin/env bash
    set -euo pipefail
    errors=0
    for f in init.el lisp/init-*.el; do
        echo "Compiling $f..."
        if ! {{emacs_bin}} --init-directory {{init_dir}} --batch \
            --eval "(setq byte-compile-error-on-warn nil)" \
            -f batch-byte-compile "$f" 2>&1; then
            errors=$((errors + 1))
        fi
    done
    # Clean up .elc files (we don't want them in the repo)
    find . -name "*.elc" -not -path "./elpaca/*" -delete 2>/dev/null || true
    if [ "$errors" -gt 0 ]; then
        echo "COMPILE FAILED: $errors file(s) had errors"
        exit 1
    fi
    echo "All files compiled successfully."

# Run ERT tests (keybinding safety + module health + no-littering)
test-ert:
    {{emacs_bin}} --init-directory {{init_dir}} --batch \
        -l ert \
        -l tests/run-tests.el

# Render the "w" work agenda over org fixtures and assert on the visible lines.
# Separate from `test-ert': it puts org-super-agenda on load-path by hand, because
# elpaca never activates an `:after org' package in batch. Fixtures live in
# temporary-file-directory — this touches nothing under second-brain.
test-work-agenda:
    {{emacs_bin}} --init-directory {{init_dir}} --batch \
        -l ert \
        -l tests/work-agenda-render.el

# Runs real processes and timers, so it is kept out of `test'.
# Drive the claude-loop state machine against a stub CLI (no API calls).
# It IS in `are-verify fast': it needs no packages and takes 3s. See FAIL-0004.
test-claude-loop:
    RATA_ROOT={{init_dir}} {{emacs_bin}} -Q --batch -l tests/claude-loop-e2e.el

# Run all tests (lint + compile + startup + ERT)
# Left exactly as it was on purpose — README, AGENTS.md and habit refer to it.
# The pre-commit gate runs `are-verify full', which is a superset. See DECISIONS D-004.
test: lint compile batch test-ert test-work-agenda

# --- ARE (Autonomous Reliability Engineering) -------------------------------
# Entry point: .are/INDEX.md   Operating manual: .are/SYSTEM.md

# Generate task context from git state + the ARE path map (.are/generated/CURRENT_CONTEXT.md)
are-context task="":
    ./scripts/are-context.sh "{{task}}"

# Repo-wide reliability audit — looks wider than the current diff
are-audit:
    ./scripts/are-audit.sh

# Renumber the knowledge pages' source-line citations after moving code around.
# The audit reports them stale; this fixes them. Run it before `are-audit', not instead.
are-fix-refs:
    ./scripts/are-fix-line-refs.sh

# Risk-based verification: fast (~4s) | relevant (~1.8min) | full (~3min)
are-verify level="fast":
    ./scripts/are-verify.sh {{level}}

# Show the ARE entry point
are:
    @echo "ARE entry point:      .are/INDEX.md"
    @echo "Operating manual:     .are/SYSTEM.md"
    @echo "Path map:             .are/knowledge/MODULES.md"
    @echo "Failure index:        .are/memory/FAILURE_INDEX.md"
    @echo ""
    @echo "  just are-context ['task']   generate task context before coding"
    @echo "  just are-verify fast        ~4s   LOW risk / mid-work"
    @echo "  just are-verify relevant    ~2min MEDIUM risk / any lisp change"
    @echo "  just are-verify full        ~3min HIGH+CRITICAL / end of session"
    @echo "  just are-audit              ~1s   repo-wide checks"
    @echo "  just are-fix-refs           renumber knowledge source-line citations"

# Configure git to use .githooks/ for hooks (one-time setup)
install-hooks:
    git config core.hooksPath .githooks
    @echo "Git hooks installed from .githooks/"

# --- repomix (packed repo context for coding agents) ------------------------
# repomix-output.xml is a generated artifact: gitignored, per-machine, and
# regenerated on demand. It is a *navigation* aid — the authoritative map of
# this config is .are/knowledge/MODULES.md plus `just are-context'.

# Set up repomix on this machine (one-time): check prerequisites, then first pack
install-repomix:
    #!/usr/bin/env bash
    set -euo pipefail

    # No global npm install is required: `npx --yes' fetches repomix on demand
    # and caches it. A globally installed binary is used when present.
    if command -v repomix &>/dev/null; then
        echo "Using repomix from PATH: $(command -v repomix)"
    elif command -v npx &>/dev/null; then
        echo "No repomix binary on PATH; will run it through npx (node $(node --version))."
        echo "For a faster start-up: npm install -g repomix"
    else
        echo "FAIL: neither repomix nor npx found. Install Node.js first" >&2
        echo "      (Arch: sudo pacman -S nodejs npm, or use nvm)." >&2
        exit 1
    fi

    [ -f repomix.config.json ] \
        && echo "Config present: repomix.config.json" \
        || { echo "FAIL: repomix.config.json is missing from the repo." >&2; exit 1; }

    git check-ignore -q repomix-output.xml \
        && echo "Output is gitignored: repomix-output.xml" \
        || echo "WARN: repomix-output.xml is not gitignored — add it to .gitignore."

    just repomix

# Regenerate repomix-output.xml (run after significant changes)
repomix:
    #!/usr/bin/env bash
    set -euo pipefail
    if command -v repomix &>/dev/null; then
        repomix
    elif command -v npx &>/dev/null; then
        npx --yes repomix
    else
        echo "FAIL: repomix unavailable. Run 'just install-repomix' for the prerequisites." >&2
        exit 1
    fi
