#!/usr/bin/env bash
# are-context.sh --- generate task-specific ARE context.
#
#   ./scripts/are-context.sh ["task description"]
#   just are-context ["task description"]
#
# Writes .are/generated/CURRENT_CONTEXT.md and echoes it to stdout.
#
# Deterministic retrieval only: git state, the path map in .are/knowledge/MODULES.md, and
# grep over the failure records. No scanning of the tree, no semantic search. The output is
# deliberately short — it tells an agent which knowledge to open, it does not inline it.

set -euo pipefail

# shellcheck source=scripts/are-lib.sh
source "$(cd "$(dirname "$0")" && pwd)/are-lib.sh"

TASK="${1:-${ARE_TASK:-}}"
OUT="$ARE_DIR/generated/CURRENT_CONTEXT.md"
mkdir -p "$(dirname "$OUT")"

changed_raw="$(are_changed_files)"
if [ -z "$changed_raw" ]; then
    changed_count=0
else
    changed_count="$(printf '%s\n' "$changed_raw" | wc -l | tr -d ' ')"
fi

max_risk=0
max_level=0
mapped=""
unmapped=""
areas=""
knowledge=""

if [ "$changed_count" -gt 0 ]; then
    while IFS= read -r file; do
        [ -n "$file" ] || continue
        if row="$(are_lookup "$file")"; then
            IFS=$'\t' read -r _pattern area risk verify know <<<"$row"
            mapped+="| \`$file\` | $area | $risk | $verify |"$'\n'
            r="$(are_risk_rank "$risk")"
            [ "$r" -gt "$max_risk" ] && max_risk="$r"
            l="$(are_level_rank "$verify")"
            [ "$l" -gt "$max_level" ] && max_level="$l"
            areas+="$area"$'\n'
            [ -n "$know" ] && knowledge+="$know"$'\n'
        else
            unmapped+="- \`$file\`"$'\n'
        fi
    done <<<"$changed_raw"
fi

# Risk tier is the maximum over changed paths; the required level is the stricter of the
# map's VERIFY column and what the risk tier demands (rules/VERIFICATION_RULES.md s1).
risk_name="$(are_risk_name "$max_risk")"
level_from_risk="$(are_level_for_risk "$risk_name")"
lr="$(are_level_rank "$level_from_risk")"
[ "$lr" -gt "$max_level" ] && max_level="$lr"
level_name="$(are_level_name "$max_level")"

# NB: `paste -sd', '` treats ", " as a *cycling list* of delimiters, so it alternates
# comma and space and mangles the list. Join with a single delimiter, then space it out.
areas_uniq="$(printf '%s' "$areas" | tr ',' '\n' | sed 's/^ *//;s/ *$//;/^$/d' | sort -u | paste -sd',' - | sed 's/,/, /g')"
knowledge_uniq="$(printf '%s' "$knowledge" | sed '/^$/d' | sort -u)"

# Relevant failure history: a record is relevant when it names a changed path or a changed
# path's basename. Cheap, deterministic, and it will not drag in unrelated history.
failures=""
if [ "$changed_count" -gt 0 ] && [ -d "$ARE_DIR/memory/failures" ]; then
    while IFS= read -r file; do
        [ -n "$file" ] || continue
        base="$(basename "$file")"
        while IFS= read -r rec; do
            [ -n "$rec" ] || continue
            failures+="$(basename "$rec" .md)"$'\n'
        done < <(grep -rls -e "$file" -e "$base" "$ARE_DIR/memory/failures/" 2>/dev/null || true)
    done <<<"$changed_raw"
fi
failures_uniq="$(printf '%s' "$failures" | sed '/^$/d' | sort -u)"

{
    echo "# CURRENT_CONTEXT"
    echo
    echo "Generated by \`just are-context\`. Regenerate rather than trusting the timestamp."
    echo "This is a pointer document: open only the knowledge and records it names."
    echo
    echo "| | |"
    echo "|---|---|"
    echo "| Generated | $(date -u '+%Y-%m-%d %H:%M UTC') |"
    echo "| Checkout | \`$ARE_REPO_ROOT\` |"
    echo "| Branch | \`$(are_branch)\` @ \`$(are_head)\` |"
    echo "| Task | ${TASK:-_(not stated — pass it as an argument)_} |"
    echo "| Changed paths | $changed_count |"
    echo "| **Risk tier** | **$risk_name** |"
    echo "| **Required verification** | **\`just are-verify $level_name\`** |"
    echo

    if [ "$changed_count" -eq 0 ]; then
        echo "## No changes vs HEAD"
        echo
        echo "Nothing is modified, staged or untracked. Risk is reported as LOW by default."
        echo "Once you start editing, re-run \`just are-context\` to get a real tier."
        echo
    else
        echo "## Changed paths"
        echo
        echo "| Path | Area | Risk | Verify |"
        echo "|---|---|---|---|"
        printf '%s' "$mapped"
        echo

        if [ -n "$unmapped" ]; then
            echo "### Unmapped — add rows to \`.are/knowledge/MODULES.md\`"
            echo
            echo "These paths are not in the path map, so their risk is unknown and this"
            echo "context is incomplete. Adding them is part of finishing the task"
            echo "(\`.are/SYSTEM.md\` s3, item 4)."
            echo
            printf '%s' "$unmapped"
            echo
        fi

        echo "**Affected areas:** ${areas_uniq:-none}"
        echo
    fi

    echo "## Knowledge to read"
    echo
    if [ -n "$knowledge_uniq" ]; then
        while IFS= read -r k; do
            [ -n "$k" ] && echo "- \`.are/$k\`"
        done <<<"$knowledge_uniq"
    else
        echo "- \`.are/INDEX.md\` only."
    fi
    echo
    echo "Do not read the whole knowledge base. Conventions and per-module reference live in"
    echo "\`AGENTS.md\`, not here. \`SPEC.md\` is drifted — grep it, never read it whole."
    echo

    echo "## Relevant failure history"
    echo
    if [ -n "$failures_uniq" ]; then
        while IFS= read -r f; do
            [ -n "$f" ] && echo "- [\`$f\`](../memory/failures/$f.md)"
        done <<<"$failures_uniq"
    else
        echo "- None recorded for these paths. Index: \`.are/memory/FAILURE_INDEX.md\`"
    fi
    echo

    echo "## Rules that apply"
    echo
    echo "- Risk classification: \`.are/rules/RISK_RULES.md\`"
    echo "- Required depth and reporting format: \`.are/rules/VERIFICATION_RULES.md\`"
    if [ "$max_risk" -ge 2 ]; then
        echo "- **$risk_name risk — read \`.are/rules/SAFETY_RULES.md\` before running anything.**"
    fi
    if [ "$max_risk" -ge 3 ]; then
        echo "- **CRITICAL — operator approval required, plus a new case in"
        echo "  \`tests/claude-loop-e2e.el\` covering the changed behaviour.**"
    fi
    echo

    echo "## Verification for this change"
    echo
    echo '```sh'
    echo "just are-verify $level_name"
    echo '```'
    echo
    case "$level_name" in
        fast) echo "Steps: lint (0.5s) + claude-loop e2e (3s) + are-audit (~1s). No packages loaded." ;;
        relevant) echo "Steps: fast + compile (24s) + ERT (78s). ~1.8 min." ;;
        full) echo "Steps: relevant + batch startup (70s). ~3 min." ;;
    esac
    echo
    echo "Report PASS / FAIL / NOT TESTED per area. Never report PASS for a command you did"
    echo "not run; integrations are always NOT TESTED here."
    echo
    echo "## Before you close the task"
    echo
    echo "Run through \`.are/SYSTEM.md\` s3. At minimum: does this work justify a failure"
    echo "record, a lesson, a decision, a path-map row, or a check that would have caught it"
    echo "sooner? Apply the cheap ones now."
} > "$OUT"

cat "$OUT"
echo
echo "--- written to $OUT"
